version: "3.8"
services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: on-failure
    volumes:
      - D:/elastic_data/:/usr/share/elasticsearch/data/
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: on-failure
    volumes:
      - D:/logstash_data/:/logstash_dir
    command: logstash -f ./logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - 9600:9600
  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: on-failure
    ports:
      - 5061:5061
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  venko:
    # depends_on:
    #   - mysqldb
    build: ./Venko
    container_name: venko-be
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "$MYSQL_AUTO_DDL"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    # mysqldb:
    #   image: mysql:5.7
    #   restart: unless-stopped
    #   env_file: ./.env
    #   environment:
    #     - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    #     - MYSQL_DATABASE=$MYSQLDB_DATABASE
    #   ports:
    #     - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    #   volumes:
    #     - db:/var/lib/mysql
volumes:
  # db:
  elastic_data: {}